PTKidsBITRobot.motorWrite(Motor_Write.Motor_Left, 100)
basic.pause(500)
PTKidsBITRobot.motorWrite(Motor_Write.Motor_Right, -100)
basic.pause(500)
PTKidsBITRobot.motorStop()
basic.pause(500)
PTKidsBITRobot.Turn(_Turn.Left, 100)
basic.pause(500)
PTKidsBITRobot.Spin(_Spin.Right, 100)
basic.pause(500)
PTKidsBITRobot.servoWrite(Servo_Write.P8, 180)
basic.pause(500)
PTKidsBITRobot.servoWrite(Servo_Write.P8, 90)
basic.forever(function () {
    basic.showNumber(PTKidsBITRobot.ADCRead(ADC_Read.ADC0))
})